{% set version = "0.3.1" %}

package:
  name: pyugrid
  version: {{ version }}

source:
  url: https://github.com/pyugrid/pyugrid/archive/v{{ version }}.tar.gz
  sha256: caac842c85b29c002f8d935c0ec293156c5e5c4dcc230a62e06639fdaecc1de6

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - netcdf4

test:
  imports:
    - pyugrid

about:
  home: https://github.com/pyugrid/pyugrid
  license: BSD 3-Clause
  summary: 'A Python API to utilize data written using the unstructured grid UGRID conventions.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - ChrisBarker-NOAA
