{% set version = "0.3.0" %}

package:
  name: pyugrid
  version: {{ version }}

source:
  fn: pyugrid-{{ version }}.tar.gz
  url: https://github.com/pyugrid/pyugrid/archive/v{{ version }}.tar.gz
  sha256: da10953f66fec2320688790f63332b8458952742694ff6e4daa765d2ea6bdcde

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - netcdf4

test:
  imports:
    - pyugrid
  commands:
    - conda inspect linkages -p $PREFIX pyugrid  # [not win]
    - conda inspect objects -p $PREFIX pyugrid  # [osx]

about:
  home: https://github.com/pyugrid/pyugrid
  license: BSD 3-Clause
  summary: 'A Python API to utilize data written using the unstructured grid UGRID conventions.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - ChrisBarker-NOAA
