{% set version = "0.2.2" %}
{% set sha256 = "5fae6642c44fabb7caf945e2145e869d1e04832d399656f36721b6235d537670"%}

package:
    name: pyugrid
    version: {{ version }}

source:
    fn: pyugrid-{{ version }}.tar.gz
    url: https://github.com/pyugrid/pyugrid/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - netcdf4

test:
    imports:
        - pyugrid

about:
    home: https://github.com/pyugrid/pyugrid
    license: BSD
    summary: A Python API to utilize data written using the unstructured grid UGRID conventions.

extra:
    recipe-maintainers:
        - pelson
        - rhattersley
        - ocefpaf
        - ChrisBarker-NOAA
