travis:
  secure:
    BINSTAR_TOKEN: bn5LJq+e0rzjQjvAk2We/l47uBNPcS/f39V9EiEbZ/wMObxuJ5GPh6vsb+8iU70WCaGoYCoLgEqrvtxBCVdFHWIZYWlVdurCvmdeJUuHTAnumj/wCqDl3A0UQLauWCisjcmNfwbQj5rrELh1wDTtPhoT+6YllcBJG/4eosGwso5xSrNJD8MAw3mF0RYM5NBNHleauLlMW1ItNco02HKrbekHJTHuRLg+y93D9I8bVlDLDDJVBlkdYW+0gOYk0bUWGF/Hg2mXhJkSBZhrtpzzrcQs+6bQS/Lylgcp2omxlxvGwQKMu6EaHKyV0+eCGFCnJgeJUXIMRMsy9lyKHREQMMW0MFul03bsAJ2zNEfQMQKSWeAFrrabs2dkIcnJ3aSd8O+TSuFICVdc6Ch+6CrX+j/8sTGGiCkJa/GcVPG/XV4MUuYihbsRdPDIDtPx4yS4YmpaIHL2vO5Ylcwzhu+3Z9+8NbUF8fXH9y7h0t6IDM3V0XQnf4iZBMlIn/K/gVjHgFY2nogHkws8GELk7xKE3pp/2XV35y/7HEhZsl88+8cK/0i7D3ZAWO0lg8F6Ecf87idCf1naHQ5ga6J8TAdOctoDELRnUSQ6ZoDfOhzqh1h829ZZ4IjLUAif+Sp28GFg3jy8TeZDvWC1nqrWEcitBtw6FfB0tyDjpGU6Orc0/HE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
