travis:
  secure:
    BINSTAR_TOKEN: tQttc3F3s9Rb6PwRTi5uH+h7SOfMOd6YWLl2dMWD74PvPiYnEqAhoWo/LwRRjczdvoQnvwiZKdtHIcpfBcKSe3L3uRgGlXtnl99Es67SJWm/xLP9hRSh2e9nGh8I0xy0pLKbAXtxMPJs7P0KrsoBtRXiYMULE4KpMqzXnirB3wu/p9R6akUETGIh1rC2jNODb+4xJJdYGiEyaCuMpB5i848n98fXfLDX3eGb+N3uSCPIygzLFyedGVFNBUYgN8UMfatCriMB2KRvRuvWXIgVo2Dh5kIYouDSRIwZGk7pbyzqtyH6h6fwgi5ieOBgcG0ucC1Ge2MsWjN9jj7JAWlIVg1r76sq2nN+LNTCPc+azzRLAuN7BkYxdaWlW0IQ/Pwvbpw1lJb+9QAjvVuCD5Xnyr60wuBvMJj9uNhSez58KMEtbq0JQIAhtyqN8MYMHIDyj7E3d3GU5dAFwtAsbGTURSF1OLWts4iLcPMZBxeaqSGVOvfc3WGQtF3TvelQz5NfeAj04qy/b6BztEaK3uesXMazqp4TCcGdRbZNQZvd33SqGGtwojF5LgbXu4T7ubVoK1kDhMyr+lIr2E4RUW0RImgnjgDPUdMofpncVppQPi9xLF4lEqLx3aI75bqYC7p+8FlHh/b15e46FNG/AZPYuxO3DNxmmDgK0E5rjD2kEb4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
